### ISSUE TITLE
Using OpenSSL and Defuse PHP-Encryption

### ISSUE THREAD

**Issue by badjava** [d8-contrib-modules/encrypt#60]
In this [PR](https://github.com/d8-contrib-modules/encrypt/pull/49#issuecomment-144149947), OpenSSL / Defuse is mentioned and I second this motion. Has there been any effort to making this happen and what can I do to help? 

I have standardized on using [Real AES](https://www.drupal.org/project/real_aes) for D7 but as far as I know, there is no D8 port yet. This should be the recommended default for D8 Encrypt and not require a separate module.

**Comment by rlhawk** [comment]
I am still very much interested in providing the best security in the encryption methods that are available within Encrypt. Generally speaking, that means that we should promote well-tested, established external libraries, rather than any implementations that we write ourselves. @badjava and I agree that the current best option is the Defuse library and so does Heine Deelstra, member of the Drupal Security Team and author of the Real AES module. That said, a better solution could come along at any time, so ideally we'd just provide up-to-date recommendations in the documentation for the most secure option(s) available and avoid adopting any encryption method as part of the project.

Not including any encryption methods would have many advantages:

- It would simplify the Encrypt module and makes it easier to release new versions, because it would no longer be inextricably linked to an encryption method (or methods) that were selected as the best option(s) when a particular version was released. See Encrypt for D7 and its connection with Mcrypt, for instance. 
- If a security advisory is issued that relates to a particular method, it would apply to just to the module that provides that method and not to Encrypt in general. Having a security advisory issued against Encrypt could be very damaging to its reputation and unnecessarily alarming to someone who is not even using the encryption method with the security issue.
- It's useful to be able to enable and disable modules to provide or prevent certain methods from even appearing as options for encryption. Ordinarily, one would use submodules for that sort of ability, but that solution comes with its own disadvantages.
- If a site's dependencies are being managed with Composer and an automated method (such as the Composer Merge plugin or the Composer Manager module) is employed, all dependencies that could be needed for any included methods would be added to the site. So if PHPSecLib and Defuse are included as methods within Encrypt, those external libraries will be added as dependencies, even if they aren't being used for encryption on the site.

So I propose that we trim Encrypt down to a pure API with no included encryption methods, move methods to their own projects, and provide strong recommendation within Encrypt's documentation about which methods to use.

**Comment by badjava** [comment]
I think this makes a lot of sense and I second this motion.

**Comment by badjava** [comment]
I've created a [d.o issue on Real AES](https://www.drupal.org/node/2613682) to port to D8 so that  assuming there is consensus on @rlhawk's comment above, we can then close this issue.

**Comment by rlhawk** [comment]
Great, thanks, @badjava. Maybe the title of this issue should be updated to better reflect the subject of the discussion?

**Comment by greggles** [comment]
FWIW, I see some of the merits to the points laid out by rlhawk, but if Encrypt becomes just an API then I doubt anyone will have a reason to use it. Personally I would just use Real AES and skip Encrypt.

**Comment by rlhawk** [comment]
Real AES provides an encryption method to Encrypt (and it also currently works with the AES Encryption module). On its own, it is just a library loader for Defuse and it doesn't provide any sort of API. Anyone who wants to use only Real AES will need to write all of the rest of the code to actually encrypt something and deal with retrieving keys. Encrypt has the advantage of an ecosystem of modules that integrate with it to manage handling keys and encryption of specific pieces of data within Drupal.

**Comment by rlhawk** [comment]
Greg points out that Real AES provides *replacement* functions for AES Encryption's aes_encrypt and aes_decrypt functions.

**Comment by HeineDeelstra** [comment]
This makes a lot of sense. Real AES really needs encrypt for it to be useful. The AES compatiblity module is just there to provide something better to people needing aes_encrypt/decrypt.

**Comment by greggles** [comment]
@HeineDeelstra thanks for the feedback. Can you clarify what you see as the features of the encrypt integration that are most important?

I feel like the key management feature is helpful and the UI makes people more comfortable.

**Comment by HeineDeelstra** [comment]
I like how one can write an encrypt plugin and have it work with modules using the Encrypt API such as webform encrypt.

**Comment by rlhawk** [comment]
The current plan is to not include any encryption method plugins with Encrypt, but to provide recommendations for what method to use for encryption and how to manage keys in a secure manner. I look forward to offering the strongest recommendation to the Real AES module and Defuse library.
